//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use super::sea_orm_active_enums::CreditOperation;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "credit_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created: DateTime,
    pub user_id: i64,
    pub operation: CreditOperation,
    pub amount: i32,
    pub balance: i32,
    pub description: Option<String>,
    pub related_user_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

