//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use super::sea_orm_active_enums::{OrderLevel, OrderStatus, PayFrom, ProductEdition};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "pay_order")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: i64,
    pub level: OrderLevel,
    pub edition: ProductEdition,
    pub pay_from: PayFrom,
    pub status: OrderStatus,
    pub created: DateTime,
    pub modified: DateTime,
    pub confirm: Option<DateTime>,
    #[sea_orm(column_type = "JsonBinary")]
    pub resp: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

