//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::account_user::Entity as AccountUser;
pub use super::favorite::Entity as Favorite;
pub use super::task_template::Entity as TaskTemplate;
