//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::account_user::Entity as AccountUser;
pub use super::favorite::Entity as Favorite;
pub use super::scraper_task::Entity as ScraperTask;
pub use super::task_template::Entity as TaskTemplate;
