//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use schemars::JsonSchema;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, JsonSchema)]
#[sea_orm(table_name = "scraper_task")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created: DateTime,
    pub modified: DateTime,
    pub user_id: i64,
    pub deleted: bool,
    pub name: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub data: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub rule: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
