//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use schemars::JsonSchema;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use strum::Display;

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: EnumString,
    JsonSchema,
    Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "product_edition")]
pub enum ProductEdition {
    #[sea_orm(string_value = "L0")]
    L0,
    #[sea_orm(string_value = "L1")]
    L1,
    #[sea_orm(string_value = "L2")]
    L2,
    #[sea_orm(string_value = "L3")]
    L3,
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: EnumString,
    JsonSchema,
    Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "template_topic")]
pub enum TemplateTopic {
    /// # 招投标
    #[sea_orm(string_value = "BIDDING")]
    Bidding,
    /// # 电商
    #[sea_orm(string_value = "E_COMMERCE")]
    ECommerce,
    /// # 本地生活
    #[sea_orm(string_value = "LOCAL_LIFE")]
    LocalLife,
    /// # 媒体
    #[sea_orm(string_value = "MEDIA")]
    Media,
    /// # 科研教育
    #[sea_orm(string_value = "RESEARCH_EDUCATION")]
    ResearchEducation,
    /// # 搜索引擎
    #[sea_orm(string_value = "SEARCH_ENGINE")]
    SearchEngine,
    /// # 社交网络
    #[sea_orm(string_value = "SOCIAL_NETWORK")]
    SocialNetwork,
    /// # 其他
    #[sea_orm(string_value = "OTHER")]
    Other,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: EnumString,
    JsonSchema,
    Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "credit_operation")]
pub enum CreditOperation {
    /// # 注册奖励
    #[sea_orm(string_value = "REGISTER")]
    Register,
    /// # 邀请奖励
    #[sea_orm(string_value = "INVITE")]
    Invite,
    /// # 数据导出
    #[sea_orm(string_value = "EXPORT")]
    Export,
    /// # 管理员调整
    #[sea_orm(string_value = "ADMIN_ADJUST")]
    AdminAdjust,
}

#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: EnumString,
    JsonSchema,
    Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "order_level")]
pub enum OrderLevel {
    /// # 月度
    #[sea_orm(string_value = "monthly")]
    Monthly,
    /// # 年度
    #[sea_orm(string_value = "annual")]
    Annual,
}

#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: EnumString,
    JsonSchema,
    Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "pay_from")]
pub enum PayFrom {
    /// # 支付宝
    #[sea_orm(string_value = "alipay")]
    Alipay,
    /// # 微信
    #[sea_orm(string_value = "wechat")]
    Wechat,
}

#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: EnumString,
    JsonSchema,
    Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "order_status")]
pub enum OrderStatus {
    /// # 已创建
    #[sea_orm(string_value = "created")]
    Created,
    /// # 已支付
    #[sea_orm(string_value = "paid")]
    Paid,
    /// # 已关闭
    #[sea_orm(string_value = "closed")]
    Closed,
}
