//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use schemars::JsonSchema;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use strum::Display;

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: EnumString,
    JsonSchema,
    Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "product_edition")]
pub enum ProductEdition {
    #[sea_orm(string_value = "L0")]
    L0,
    #[sea_orm(string_value = "L1")]
    L1,
    #[sea_orm(string_value = "L2")]
    L2,
    #[sea_orm(string_value = "L3")]
    L3,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: EnumString,
    JsonSchema,
    Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "template_topic")]
pub enum TemplateTopic {
    #[sea_orm(string_value = "BIDDING")]
    Bidding,
    #[sea_orm(string_value = "E_COMMERCE")]
    ECommerce,
    #[sea_orm(string_value = "LOCAL_LIFE")]
    LocalLife,
    #[sea_orm(string_value = "MEDIA")]
    Media,
    #[sea_orm(string_value = "OTHER")]
    Other,
    #[sea_orm(string_value = "RESEARCH_EDUCATION")]
    ResearchEducation,
    #[sea_orm(string_value = "SEARCH_ENGINE")]
    SearchEngine,
    #[sea_orm(string_value = "SOCIAL_NETWORK")]
    SocialNetwork,
}
