//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use schemars::JsonSchema;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::model::sea_orm_active_enums::InstanceStatus;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, JsonSchema)]
#[sea_orm(table_name = "task_instance")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub task_id: i64,
    pub created: DateTime,
    pub modified: DateTime,
    pub status: InstanceStatus,
    pub data_count: i32,
    pub log_key: Option<String>,
    pub error_message: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
