POST http://localhost:8888/user/register-validate-code
Content-Type: application/json

{
  "email": "hff1996723@qq.com"
}

###
POST http://localhost:8888/user/reset-validate-code
Content-Type: application/json

{
  "email": "hff1996723@qq.com"
}

###
POST http://localhost:8888/user
Content-Type: application/json

{
  "name": "holmofy",
  "email": "hff1996723@qq.com",
  "passwd": "123456",
  "validateCode": "39AZDa"
}

###
POST http://localhost:8888/token
Content-Type: application/json

{
  "email": "hff1996723@qq.com",
  "passwd": "123456"
}

###
GET http://localhost:8888/user
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOjgsImlzcyI6IkF1dG9XRFMiLCJleHAiOjE3MjQ5NzE5ODJ9.DvUdwakq8ZRMBgoANu_KQhh5wKno4xTx_oJGQp6J9N0qfJb8OUYEbqBIehvRBMMmH4jIIPPteh9RDRR1W3yfJsbeUBWxnegFh0NW24BvArVJpHTg5kL7KNLTkmFDAOblzqzVTKqw9fiehyZnxeo1ibj4XMNJ5C8y-zZt1-l4xJ9hwB2-4YJiRMJ1rlxBynahdaWpAcn0tqPHLu7b7ts_w7TgvQunxNl49WhkXEQaI7p2FnIKURh9aoavUvIsaHfqf1Q7VXLbSUsxJhZOGTDZmDoyLOlbf8vrfZzp2VqyF4XszypN5lIoGHOGJVMeBS0ivuxrd-OdVgPnXfCY8Pp3Pw

###
GET http://localhost:8888/task
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOjgsImlzcyI6IkF1dG9XRFMiLCJleHAiOjE3MjQ5NzE5ODJ9.DvUdwakq8ZRMBgoANu_KQhh5wKno4xTx_oJGQp6J9N0qfJb8OUYEbqBIehvRBMMmH4jIIPPteh9RDRR1W3yfJsbeUBWxnegFh0NW24BvArVJpHTg5kL7KNLTkmFDAOblzqzVTKqw9fiehyZnxeo1ibj4XMNJ5C8y-zZt1-l4xJ9hwB2-4YJiRMJ1rlxBynahdaWpAcn0tqPHLu7b7ts_w7TgvQunxNl49WhkXEQaI7p2FnIKURh9aoavUvIsaHfqf1Q7VXLbSUsxJhZOGTDZmDoyLOlbf8vrfZzp2VqyF4XszypN5lIoGHOGJVMeBS0ivuxrd-OdVgPnXfCY8Pp3Pw

###
POST http://localhost:8888/task
Content-Type: application/json
Authorization: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoiaGZmMTk5NjcyM0BxcS5jb20ifQ.ZjcWohSUiSXs7oImWFKdow0YssT8-XTZv2KpeTGOsnFLWK250zFGUGKxLlsJuZiN6rBZvJO4HMLby7gBQarb5f4xcLOsDExfk7z2kqBr8OEChw_gKDjH8gzrQ1ahcbyDQcbm_hzn37nIqJlQsIPOiaBWvRu94g59_bDixJawcyAe6QH_jp08U1vu18BCX4YxfsgvpVufk01WJB1V9mmnXQSLp2EofJr4lNCogO9_Opz-4ve-JLtWnAeAe5dnuRcWdMk0qxlRLyItnw3IHrIvGT2XCO-Nzjp-1dSWuK9l5bBz4lmWKSjUE-nijGyaNIuxtCh0vJn21_82gsTjXzO5yg

{
  "name":"test-task",
  "data":{
      "cron":"* * 1 * * *"
  }
}

###
PATCH http://localhost:8888/task/10
Content-Type: application/json
Authorization: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoiaGZmMTk5NjcyM0BxcS5jb20ifQ.ZjcWohSUiSXs7oImWFKdow0YssT8-XTZv2KpeTGOsnFLWK250zFGUGKxLlsJuZiN6rBZvJO4HMLby7gBQarb5f4xcLOsDExfk7z2kqBr8OEChw_gKDjH8gzrQ1ahcbyDQcbm_hzn37nIqJlQsIPOiaBWvRu94g59_bDixJawcyAe6QH_jp08U1vu18BCX4YxfsgvpVufk01WJB1V9mmnXQSLp2EofJr4lNCogO9_Opz-4ve-JLtWnAeAe5dnuRcWdMk0qxlRLyItnw3IHrIvGT2XCO-Nzjp-1dSWuK9l5bBz4lmWKSjUE-nijGyaNIuxtCh0vJn21_82gsTjXzO5yg

{
  "name": "modified-task-name"
}

###
PUT http://localhost:8888/task/10
Content-Type: application/json
Authorization: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoiaGZmMTk5NjcyM0BxcS5jb20ifQ.ZjcWohSUiSXs7oImWFKdow0YssT8-XTZv2KpeTGOsnFLWK250zFGUGKxLlsJuZiN6rBZvJO4HMLby7gBQarb5f4xcLOsDExfk7z2kqBr8OEChw_gKDjH8gzrQ1ahcbyDQcbm_hzn37nIqJlQsIPOiaBWvRu94g59_bDixJawcyAe6QH_jp08U1vu18BCX4YxfsgvpVufk01WJB1V9mmnXQSLp2EofJr4lNCogO9_Opz-4ve-JLtWnAeAe5dnuRcWdMk0qxlRLyItnw3IHrIvGT2XCO-Nzjp-1dSWuK9l5bBz4lmWKSjUE-nijGyaNIuxtCh0vJn21_82gsTjXzO5yg

{
  "name":"test-task",
  "data":{
      "cron":"* * 10 * * *"
  }
}

### 
GET http://localhost:8888/template
Authorization: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoiaGZmMTk5NjcyM0BxcS5jb20ifQ.ZjcWohSUiSXs7oImWFKdow0YssT8-XTZv2KpeTGOsnFLWK250zFGUGKxLlsJuZiN6rBZvJO4HMLby7gBQarb5f4xcLOsDExfk7z2kqBr8OEChw_gKDjH8gzrQ1ahcbyDQcbm_hzn37nIqJlQsIPOiaBWvRu94g59_bDixJawcyAe6QH_jp08U1vu18BCX4YxfsgvpVufk01WJB1V9mmnXQSLp2EofJr4lNCogO9_Opz-4ve-JLtWnAeAe5dnuRcWdMk0qxlRLyItnw3IHrIvGT2XCO-Nzjp-1dSWuK9l5bBz4lmWKSjUE-nijGyaNIuxtCh0vJn21_82gsTjXzO5yg
